Repository andela/bad_ass-ah-backend, pull requests merged in 2019-03, with the labels that each got.

#2 #164489917 Eslint Setup
  .eslintrc
  package-lock.json
  package.json
Labels: WIP

#9 #164489916 Configure postgreSQL as database engine
  .babelrc
  .env_sample
  .gitignore
  .sequelizerc
  config/config.js
  config/index.js
  config/passport.js
  index.js
  models/User.js
  models/index.js
  package-lock.json
  package.json
  routes/api/index.js
  routes/api/users.js
  routes/index.js
Labels: Finished, Ready for review

#5 #164489915 Integrate travisCi with badge attached to readme
  .travis.yml
  README.md
Labels: Finished, Ready for review

#12 #164489921 Integrate coveralls code coverage service
  .coveralls.yml
  README.md
  package-lock.json
  package.json
Labels: Finished, Ready for review

#7 #164489918 Integrate houndCI with readme badge
  .hound.yml
  README.md
Labels: Finished, Ready for review

#3 #164489920 added test environment
  .gitignore
  index.js
  package-lock.json
  package.json
  test/test.js
Labels: Finished, Ready for review

#16 164489925 added user validation
  helpers/validateUser.js
Labels: Finished
