Repository andela/bad_ass-ah-backend, pull requests merged in 2019-04, with the labels that each got.

#18 # 164489919 Deployment to Heroku
  Procfile
  package.json
Labels: Ready for review

#19 #164489924 send a verification link to the user's email account
  .env_sample
  config/config.js
  controllers/email/verifyLink.js
  controllers/user.js
  helpers/sendEmail/callMailer.js
  helpers/sendEmail/emailTemplates.js
  helpers/sendEmail/mailer.js
  index.js
  migrations/20190326112352-user.js
  models/user.js
  package-lock.json
  package.json
  routes/api/index.js
  routes/api/users.js
  test/sendEmail.test.js
  test/user.js
  testingdata/user.json
Labels: Ready for review

#22 #165082475 user login
  .env_sample
  .eslintrc
  config/config.js
  controllers/user.js
  package-lock.json
  routes/api/users.js
  test/test.js
  test/user.js
  testingdata/user.json
Labels: Ready for review

#25 #164489925 User validations
  helpers/validate.js
  helpers/validateUser.js
  middlewares/user.js
  routes/api/users.js
  test/user.js
  test/validate.test.js
  testingdata/user.json
Labels: Finished, Ready for review

#17 #164516500 Enable social login via google
  .eslintrc
  config/config.js
  controllers/user.js
  index.js
  middlewares/passport-google.js
  migrations/20190326112352-user.js
  models/user.js
  package-lock.json
  package.json
  routes/api/users.js
  routes/index.js
  test/sendEmail.test.js
  test/user.js
  testingdata/user.json
Labels: Ready for review

#20 #[164489928] Login user using facebook
  .eslintrc
  config/index.js
  config/passport.js
  controllers/user.js
  helpers/token.js
  index.js
  middlewares/passport-facebook.js
  migrations/20190326112352-user.js
  package-lock.json
  package.json
  routes/api/auth/facebook.js
  routes/index.js
  test/user.js
  testingdata/user.json
Labels: Ready for review

#23 #164489930 create-view articles
  controllers/article.js
  controllers/user.js
  index.js
  middlewares/multerConfiguration.js
  middlewares/passport-jwt.js
  migrations/20190402140158-article.js
  models/article.js
  models/user.js
  package-lock.json
  package.json
  routes/api/article.js
  routes/index.js
  test/artilcle.js
  test/user.js
  testingdata/andela.png
  testingdata/article.json
  testingdata/user.json
Labels: Ready for review

#28 #165174100 Edit-Delete article
  controllers/article.js
  middlewares/article.js
  middlewares/user.js
  migrations/20190402140158-article.js
  package.json
  routes/api/article.js
  test/0-test.js
  test/1-user.js
  test/2-sendEmail.test.js
  test/3-artilcle.js
  test/4-validate.test.js
  test/artilcle.js
Labels: Finished, Ready for review

#31 #164489940 list users
  .env_sample
  controllers/user.js
  package.json
  routes/api/users.js
  test/1-sendEmail.test.js
  test/2-user.js
  testingdata/user.json
Labels: Finished, Ready for review

#30 #164489934 comment an article
  controllers/comment.js
  helpers/validateComment.js
  index.js
  middlewares/checkArticle.js
  middlewares/checkComment.js
  migrations/20190402140158-article.js
  migrations/20190408131611-create-comments.js
  models/article.js
  models/comments.js
  models/user.js
  package.json
  routes/api/article.js
  test/1-user.js
  test/2-sendEmail.test.js
  test/5-comment.js
  testingdata/comment.json
Labels: Finished, Ready for review

#29 #164489929 create user profile
  controllers/user.js
  routes/api/users.js
  test/1-sendEmail.test.js
  test/1-user.js
  test/2-user.js
  test/6-comment.js
  testingdata/user.json
Labels: Finished, Ready for review

#34 #164489943 getting article reading time
  controllers/article.js
  helpers/readingTime.js
  migrations/20190402140158-article.js
  migrations/20190408131611-create-comments.js
  migrations/20190409161017-create-rate.js
  models/article.js
  testingdata/user.json
Labels: Finished, Ready for review

#38 #164489944 share an article across some channels
  controllers/user.js
  helpers/shareArticles.js
  package.json
  routes/api/article.js
  test/3-artilcle.js
  testingdata/user.json
Labels: Finished, Ready for review

#36 #164489942 search functionalities
  controllers/article.js
  controllers/search.js
  helpers/search.js
  helpers/tags.js
  routes/api/search.js
  routes/index.js
  test/2-user.js
  test/3-artilcle.js
  testingdata/article.json
  testingdata/user.json
Labels: Ready for review

#37 #164489936 Followers
  controllers/followers.js
  middlewares/followers.js
  migrations/20190416160231-followers.js
  models/followers.js
  models/rate.js
  routes/api/users.js
  test/8-followers.js
  testingdata/user.json
Labels: Ready for review, WIP

#39 #164489946 Reports a particular article
  controllers/report/reportArticle.js
  controllers/user.js
  helpers/sendEmail/emailTemplates.js
  middlewares/userAccount.js
  migrations/20190415122944-create-report-types.js
  migrations/20190415140154-create-report-article.js
  models/article.js
  models/reportArticle.js
  models/reportType.js
  models/user.js
  routes/api/article.js
  routes/api/report.js
  routes/index.js
  test/8-reportArticle.js
  testingdata/reportArticle.json
  testingdata/user.json
Labels: Ready for review

#32 #164489935 Allowing users to like or dislike articles.
  controllers/article.js
  controllers/votes.js
  helpers/tags.js
  middlewares/isAuth.js
  middlewares/votes.js
  migrations/20190409175130-Vote.js
  models/article.js
  models/votes.js
  routes/api/article.js
  test/3-artilcle.js
  test/6-likes.test.js
  test/8-comment.js
  testingdata/user.json
Labels: Finished, Ready for review

#44 # 165525869 Bug-fix for password reset validation
  middlewares/passwordValidate.js
  routes/api/article.js
  routes/api/users.js
  test/5-passwordReset.test.js
  testingdata/user.json
Labels: Ready for review

#46 #165525952 Fix bug for twitter login
  .vscode/launch.json
  controllers/comment.js
  helpers/shareArticles.js
  middlewares/passport-twitter.js
  package.json
  test/3-artilcle.js
  testingdata/user.json
Labels: Finished, Ready for review

#47 #165525344 Fix Username Signup Validation
  Procfile
  helpers/validate.js
  models/followers.js
  package.json
  test/2-user.js
  testingdata/user.json
Labels: Ready for review

#43 #164489948 users reading stats
  .gitignore
  controllers/article.js
  controllers/stats/articleStats.js
  helpers/search.js
  migrations/20190418055830-create-article-stats.js
  models/article.js
  models/articleStats.js
  models/user.js
  routes/api/article.js
  routes/api/users.js
  test/1-sendEmail.test.js
  test/3-artilcle.js
  test/7-rate.test.js
  testingdata/user.json
Labels: Ready for review

#41 #165374381 Fix Migrations
  controllers/article.js
  controllers/followers.js
  helpers/validateUser.js
  middlewares/followers.js
  migrations/20190326112352-user.js
  routes/api/users.js
  test/8-followers.js
  testingdata/user.json
Labels: Ready for review

#42 Feature(notifications): receive notifications
  controllers/article.js
  controllers/comment.js
  controllers/notification.js
  helpers/notifications/check.js
  helpers/sendEmail/emailTemplates.js
  helpers/sendEmail/mailer.js
  migrations/20190416092515-create-notification.js
  migrations/20190418065608-add-allowNotification-to-user.js
  models/notification.js
  models/user.js
  package.json
  routes/api/users.js
  test/2-user.js
  test/8-comment.js
  test/9-followers.js
  test/9-notification.js
  test/9-reportArticle.js
Labels: Finished, Ready for review

#40 #164489939 Pagination support for articles
  controllers/article.js
  testingdata/user.json
Labels: Finished, Ready for review

#48 #165525643 fix email verification and login after verifying email account
  .env_sample
  controllers/user.js
  helpers/sendEmail/emailTemplates.js
  helpers/sendEmail/mailer.js
  index.js
  test/1-sendEmail.test.js
  test/2-user.js
  test/3-artilcle.js
  test/6-likes.test.js
  test/7-rate.test.js
  test/8-comment.js
  test/9-followers.js
  test/9-notification.js
  test/9-reportArticle.js
  testingdata/user.json
Labels: Finished, Ready for review

#45 #164489933 Pagination support for ratings
  controllers/rate.js
  test/7-rate.test.js
  testingdata/user.json
Labels: Finished, Ready for review

#49 #164489949 Role Based Access Control
  controllers/followers.js
  controllers/user.js
  helpers/activation.js
  index.js
  middlewares/followers.js
  middlewares/user.js
  middlewares/userAccount.js
  migrations/20190424162035-userStatus.js
  migrations/20190429110729-isManager.js
  models/user.js
  routes/api/report.js
  routes/api/users.js
  test/2-user.js
  test/w-reportArticle.js
  test/z-user-permission.js
  testingdata/user.json
Labels: Ready for review
